brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
listenPort=10911
autoCreateTopicEnable=false
autoCreateSubscriptionGroup=true
brokerRole=ASYNC_MASTER
flushDiskType=SYNC_FLUSH
mapedFileSizeCommitLog=67108864
diskMaxUsedSpaceRatio=95
